"""create user table

Revision ID: 9327ce6829fd
Revises: 
Create Date: 2025-12-24 21:07:45.074838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9327ce6829fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type safely
    user_role = sa.Enum('superadmin', 'admin', 'user', name='user_role')
    try:
        user_role.create(op.get_bind(), checkfirst=True)
    except sa.exc.ProgrammingError as e:
        if "DuplicateObjectError" not in str(e) and 'type "user_role" already exists' not in str(e):
            raise
        print("Enum 'user_role' already exists, skipping creation.")

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', postgresql.ENUM('superadmin', 'admin', 'user', name='user_role', create_type=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_user_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_index('idx_user_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_username', table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_is_active', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
